config/routes.rb
Rails.application.routes.draw do
 
  root 'users#index'

  delete '/logout', to: 'sessions#destroy'

  get '/login', to: 'sessions#new'

  resources :sessions, only: [:new, :create, :destroy]

  resources :users

  resources :photos
end
  

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :photos
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user


  def current_user
    #find will error with nil, find_by will not error with nil
    @current_user ||= User.find_by(id: session[:user_id]) 
  end

  def logged_in?
    !!current_user
  end

  def authenticate
    unless logged_in?
      flash[:error] = "You must be logged in buddy"
      redirect_to login_url
    end
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
 
  def index
  end

  def new
    @photo = current_user.photos.new
  end

  def create
    @photo = current_user.photos.new(photo_params)
    if @photo.save
      redirect_to user_path(current_user)
    else 
      render 'new'
    end
  end

  def edit
  end

  def create
  end

  def show
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'YOU ARE IN!'
    else 
      flash.now.alert = 'Wrong you shall not pass!'
      render 'new'
    end
  end

  def destroy 
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged Out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      redirect_to users_path
    else 
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id]) 
    @user_photos = @user.photos
  end
    
private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlickrApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <%#= image_tag "pikachu.png", class: 'banner' %>

  <% flash.each do |name, message| %>
    <div class="flash-message flash-message-<%= name %>">
      <%= message %>
    </div>
  <% end %>

  <% if current_user %> 
    <p> Hello, <%= current_user.email %></p>

    <%= link_to 'Add Photo', new_photo_path %>
    <%= link_to 'All Users', users_path %> 
    <%= link_to 'Your Profile', user_path(current_user) %>  
    <%= link_to 'Logout', logout_path, method: :delete, data: {confirm: "Are you sure?"} %>
  <% else %>
    <%= link_to 'Sign Up', new_user_path %>
    <%= link_to 'Please login', login_path %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/photos/edit.html.erb
PHOTOS EDIT

app/views/photos/new.html.erb
<h1>New Photos</h1>

<%= form_for @photo do |f| %> 
  <%= f.text_field :title %>
  <%= f.text_field :url  %>
  <%= f.submit %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Welcome to Pikchur</h1>


<% @users.each do |user| %> 

  <p> 
    <%= user.email %> 
    <br/> 
  <%= link_to 'View Profile', user_path(user) %>
  </p> 

<% end %> 

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %> 
<% if @user.errors.any? %>
  <div class="error_messages">
    <h2>Form is invalid</h2>
    <ul> 
      <% for message in @user.errors.
        full_messages %> 
        <li><%= message %></li> 
      <% end %>
    </ul>
  </div>
<% end %>
<div class= "field"> 
  Name
  <%= f.text_field :name%>
  <br>
  <%= f.label :email %> 
  <%= f.text_field :email %>
</div> 
<div class="field">
  <%= f.label :password %> 
  <%= f.password_field :password %> 
</div> 

<div class="field">
  <%= f.label :password_confirmation %> 
  <%= f.password_field :password_confirmation %> 
</div> 
<div class="actions"><%= f.submit %></div> 
<% end %> 

app/views/users/show.html.erb
<h4>this is <%= @user.name %> photos</h4>



<% @user_photos.each do |photo| %>
  Title: <%= photo.title %> 
  <br>
  Url:<%= photo.url %> 
  <br>
  <% if current_user == @user %>
    <%= link_to 'edit photo', edit_photo_path(photo) %> 
  <% end %>
<% end %>
 